overview_url("Alert", notfound).
overview_url("ArcGauge", 'https://docs.telerik.com/kendo-ui/controls/gauges/arcgauge/overview').
overview_url("AutoComplete", 'https://docs.telerik.com/kendo-ui/controls/editors/autocomplete/overview').
overview_url("Barcode", 'https://docs.telerik.com/kendo-ui/controls/barcodes/barcode/overview').
overview_url("Button", 'https://docs.telerik.com/kendo-ui/controls/navigation/button/overview').
overview_url("ButtonGroup", 'https://docs.telerik.com/kendo-ui/controls/navigation/buttongroup/overview').
overview_url("Calendar", 'https://docs.telerik.com/kendo-ui/controls/scheduling/calendar/overview').
overview_url("Chart", notfound).
overview_url("Chat", 'https://docs.telerik.com/kendo-ui/controls/conversational-ui/chat/overview').
overview_url("ColorPalette", notfound).
overview_url("ColorPicker", 'https://docs.telerik.com/kendo-ui/controls/editors/colorpicker/overview').
overview_url("ComboBox", 'https://docs.telerik.com/kendo-ui/controls/editors/combobox/overview').
overview_url("Confirm", notfound).
overview_url("ContextMenu", notfound).
overview_url("DateInput", 'https://docs.telerik.com/kendo-ui/controls/editors/dateinput/overview').
overview_url("DatePicker", 'https://docs.telerik.com/kendo-ui/controls/editors/datepicker/overview').
overview_url("DateTimePicker", 'https://docs.telerik.com/kendo-ui/controls/editors/datetimepicker/overview').
overview_url("Diagram", notfound).
overview_url("Dialog", 'https://docs.telerik.com/kendo-ui/controls/layout/dialog/overview').
overview_url("Draggable", notfound).
overview_url("DropDownList", 'https://docs.telerik.com/kendo-ui/controls/editors/dropdownlist/overview').
overview_url("DropDownTree", 'https://docs.telerik.com/kendo-ui/controls/editors/dropdowntree/overview').
overview_url("DropTarget", notfound).
overview_url("DropTargetArea", notfound).
overview_url("Editor", 'https://docs.telerik.com/kendo-ui/controls/editors/editor/overview').
overview_url("FilterMenu", notfound).
overview_url("FlatColorPicker", notfound).
overview_url("Gantt", 'https://docs.telerik.com/kendo-ui/controls/scheduling/gantt/overview').
overview_url("Grid", 'https://docs.telerik.com/kendo-ui/controls/data-management/grid/overview').
overview_url("LinearGauge", 'https://docs.telerik.com/kendo-ui/controls/gauges/lineargauge/overview').
overview_url("ListBox", 'https://docs.telerik.com/kendo-ui/controls/editors/listbox/overview').
overview_url("ListView", 'https://docs.telerik.com/kendo-ui/controls/data-management/listview/overview').
overview_url("Map", notfound).
overview_url("MaskedTextBox", 'https://docs.telerik.com/kendo-ui/controls/editors/maskedtextbox/overview').
overview_url("MediaPlayer", 'https://docs.telerik.com/kendo-ui/controls/media/mediaplayer/overview').
overview_url("Menu", 'https://docs.telerik.com/kendo-ui/controls/navigation/menu/overview').
overview_url("MobileActionSheet", 'https://docs.telerik.com/kendo-ui/controls/hybrid/actionsheet/actionsheet').
overview_url("MobileBackButton", notfound).
overview_url("MobileButton", 'https://docs.telerik.com/kendo-ui/controls/hybrid/button/button').
overview_url("MobileButtonGroup", 'https://docs.telerik.com/kendo-ui/controls/hybrid/buttongroup/buttongroup').
overview_url("MobileCollapsible", 'https://docs.telerik.com/kendo-ui/controls/hybrid/collapsible/collapsible').
overview_url("MobileDetailButton", notfound).
overview_url("MobileDrawer", 'https://docs.telerik.com/kendo-ui/controls/hybrid/drawer/drawer').
overview_url("MobileLayout", notfound).
overview_url("MobileListView", notfound).
overview_url("MobileLoader", notfound).
overview_url("MobileModalView", 'https://docs.telerik.com/kendo-ui/controls/hybrid/modalview/modalview').
overview_url("MobileNavBar", 'https://docs.telerik.com/kendo-ui/controls/hybrid/navbar/navbar').
overview_url("MobilePane", 'https://docs.telerik.com/kendo-ui/controls/hybrid/pane/pane').
overview_url("MobilePopOver", 'https://docs.telerik.com/kendo-ui/controls/hybrid/popover/popover').
overview_url("MobileScroller", 'https://docs.telerik.com/kendo-ui/controls/hybrid/scroller/scroller').
overview_url("MobileScrollView", notfound).
overview_url("MobileSplitView", 'https://docs.telerik.com/kendo-ui/controls/hybrid/splitview/splitview').
overview_url("MobileSwitch", 'https://docs.telerik.com/kendo-ui/controls/hybrid/switch/switch').
overview_url("MobileTabStrip", 'https://docs.telerik.com/kendo-ui/controls/hybrid/tabstrip/tabstrip').
overview_url("MobileView", 'https://docs.telerik.com/kendo-ui/controls/hybrid/view/view').
overview_url("MultiColumnComboBox", 'https://docs.telerik.com/kendo-ui/controls/editors/multicolumncombobox/overview').
overview_url("MultiSelect", 'https://docs.telerik.com/kendo-ui/controls/editors/multiselect/overview').
overview_url("Notification", 'https://docs.telerik.com/kendo-ui/controls/layout/notification/overview').
overview_url("NumericTextBox", 'https://docs.telerik.com/kendo-ui/controls/editors/numerictextbox/overview').
overview_url("Pager", notfound).
overview_url("PanelBar", 'https://docs.telerik.com/kendo-ui/controls/navigation/panelbar/overview').
overview_url("PivotConfigurator", notfound).
overview_url("PivotGrid", 'https://docs.telerik.com/kendo-ui/controls/data-management/pivotgrid/overview').
overview_url("Popup", 'https://docs.telerik.com/kendo-ui/controls/layout/popup/overview').
overview_url("ProgressBar", 'https://docs.telerik.com/kendo-ui/controls/interactivity/progressbar/overview').
overview_url("Prompt", notfound).
overview_url("QRCode", 'https://docs.telerik.com/kendo-ui/controls/barcodes/qrcode/overview').
overview_url("RadialGauge", 'https://docs.telerik.com/kendo-ui/controls/gauges/radialgauge/overview').
overview_url("RangeSlider", 'https://docs.telerik.com/kendo-ui/controls/editors/rangeslider/overview').
overview_url("ResponsivePanel", 'https://docs.telerik.com/kendo-ui/controls/layout/responsivepanel/overview').
overview_url("Scheduler", 'https://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/overview').
overview_url("Slider", 'https://docs.telerik.com/kendo-ui/controls/editors/slider/overview').
overview_url("Sortable", 'https://docs.telerik.com/kendo-ui/controls/interactivity/sortable/overview').
overview_url("Sparkline", 'https://docs.telerik.com/kendo-ui/controls/charts/sparkline/overview').
overview_url("Splitter", 'https://docs.telerik.com/kendo-ui/controls/layout/splitter/overview').
overview_url("Spreadsheet", 'https://docs.telerik.com/kendo-ui/controls/data-management/spreadsheet/overview').
overview_url("StockChart", 'https://docs.telerik.com/kendo-ui/controls/charts/stockchart/overview').
overview_url("TabStrip", 'https://docs.telerik.com/kendo-ui/controls/navigation/tabstrip/overview').
overview_url("TimePicker", 'https://docs.telerik.com/kendo-ui/controls/editors/timepicker/overview').
overview_url("ToolBar", 'https://docs.telerik.com/kendo-ui/controls/navigation/toolbar/overview').
overview_url("Tooltip", 'https://docs.telerik.com/kendo-ui/controls/layout/tooltip/overview').
overview_url("Touch", notfound).
overview_url("TreeList", 'https://docs.telerik.com/kendo-ui/controls/data-management/treelist/overview').
overview_url("TreeMap", 'https://docs.telerik.com/kendo-ui/controls/charts/treemap/overview').
overview_url("TreeView", 'https://docs.telerik.com/kendo-ui/controls/navigation/treeview/overview').
overview_url("Upload", 'https://docs.telerik.com/kendo-ui/controls/editors/upload/overview').
overview_url("Validator", 'https://docs.telerik.com/kendo-ui/controls/editors/validator/overview').
overview_url("Window", 'https://docs.telerik.com/kendo-ui/controls/layout/window/overview').
